services:
  - type: web
    name: telegram-quiz-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DEVELOPER_ID
        sync: false
